version: 1
services:
  - type: web
    name: my-app
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn main:app --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: TESSDATA_PREFIX
        value: "/usr/share/tesseract-ocr/4.00/tessdata"



