version: 1
services:
  - type: web
    name: my-app
    env: docker
    buildCommand: echo "No build command needed for Docker"
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0


